import React from 'react'



const Virtual1 = () => {
    // UPDATED: This component now uses `gap` for consistent spacing and `items-center` for alignment.
    const FeatureItem = ({ title, bullets, imageSrc, graphicSide = 'right' }) => (
        <div className={`flex flex-col md:flex-row items-center py-8 md:gap-16 ${graphicSide === 'left' ? 'md:flex-row-reverse' : ''}`}>
            {/* Text Content: Removed specific padding to rely on parent `gap` */}
            <div className="flex-1 mb-6 md:mb-0">
                <h3 className="text-2xl font-bold mb-4 text-gray-800">{title}</h3>
                <ul className="list-none space-y-2 pl-0">
                    {bullets.map((bullet, index) => (
                        <li key={index} className="flex items-start text-gray-600">
                            <span className="text-blue-500 text-lg mr-3 mt-1">•</span> {/* Custom bullet point */}
                            <span className="flex-1">{bullet}</span>
                        </li>
                    ))}
                </ul>
            </div>

            {/* Graphic Content */}
            <div className="flex-1 w-full max-w-lg">
                {imageSrc && (
                    <img
                        src={imageSrc}
                        alt={`Graphic for ${title}`}
                        className="w-full h-auto object-contain"
                    />
                )}
            </div>
        </div>
    );

    return (
        <div className="font-sans max-w-6xl mx-auto p-4 sm:p-8">

            {/* Header Section */}
            <header className="text-center mb-12">
                <p className="text-3xl sm:text-3xl font-semibold text-gray-700 mb-1">Meet Aurora Borea, our chatbot for intelligent customer support</p>
                <h1 className="text-3xl sm:text-3xl font-bold text-gray-900 mb-2">
                    Conversational AI Virtual Assistant: Features
                </h1>
                <p className="text-gray-600 max-w-3xl mx-auto">
                    Automate customer support and boost productivity with your virtual assistant solution.
                </p>
            </header>

            {/* Feature 1: 24/7 Personalized Customer Support */}
            <FeatureItem
                title="24/7 Personalized Customer Support"
                bullets={[
                    "Handling common questions about the company’s services and products adjusted to the specific client’s request",
                    "70% availability being able to answer basic and hectic items",
                    "Chat support being available 24/7 hours a day",
                    "Immediate comprehension response to the query based on the company’s proprietary knowledge base",
                    "Virtual assistant for the managed IT support",
                    "Recommendations concerning the topic generated by AI"
                ]}
                imageSrc="/vir1.png" // Path to your image in the public folder
                graphicSide="right"
            />

            {/* Feature 2: Automated Sales Team Support */}
            <FeatureItem
                title="Automated Sales Team Support"
                bullets={[
                    "Assists the SRA with customers to help set your human agents for sales consultation and other needs",
                    "Effective appointment scheduling across time zones",
                    "Lead data transfer to the sales team conversation history and summary",
                    "Automatic email notifications to the sales team and customer"
                ]}
                imageSrc="/vir2.png" // Path to your image in the public folder
                graphicSide="left"
            />

            {/* Feature 3: Appointment Scheduling */}
            <FeatureItem
                title="Appointment Scheduling"
                bullets={[
                    "Quick and swift conversation handling",
                    "Scheduling tasks across time zones",
                    "Calendar integration"
                ]}
                imageSrc="/vir3.png" // Path to your image in the public folder
                graphicSide="right"
            />

            {/* Feature 4: Easy Integration with CRM */}
            <FeatureItem
                title="Easy Integration with CRM"
                bullets={[
                    "Automated data extraction and summarization from conversations",
                    "Prompt creation of CRM records required",
                    "Inbound data ingestion"
                ]}
                imageSrc="/vir4.png" // Path to your image in the public folder
                graphicSide="left"
            />
            
            {/* Feature 5: Text and Voice Recognition */}
            <FeatureItem
                title="Text and Voice Recognition"
                bullets={[
                    "The ability to audio communicate your need to a chatbot",
                    "Fast and natural customer experience"
                ]}
                imageSrc="/vir5.png" // Path to your image in the public folder
                graphicSide="right"
            />

        </div>
    );
}

export default Virtual1;